# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Intqual < Formula
  desc "Dual-layer asynchronous network latency analyzer and observability tool writte"
  homepage "https://github.com/RaijuMounun/intqual"
  url "https://github.com/RaijuMounun/intqual/archive/refs/tags/v1.0.2.tar.gz"
  sha256 "6e44d1b2bb9b00c734bb78bd0e849991e7746f35ed1468312710cade5915d108"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    system "#{bin}/intqual --version"
  end
end
