# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Intqual < Formula
  desc "Dual-layer asynchronous network latency analyzer and observability tool writte"
  homepage "https://github.com/RaijuMounun/intqual"
  url "https://github.com/RaijuMounun/intqual/archive/refs/tags/v1.0.3.tar.gz"
  sha256 "c96f7687cd6fc228f1f62591913c6087b8b5d9d315fde2789005ecbcd24c3860"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    system "#{bin}/intqual --version"
  end
end
