# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Intqual < Formula
  desc "Dual-layer asynchronous network latency analyzer and observability tool writte"
  homepage "https://github.com/RaijuMounun/intqual"
  url "https://github.com/RaijuMounun/intqual/archive/refs/tags/v1.0.8.tar.gz"
  sha256 "7df89a78aa58a8fc3d688710af5573a36d8c79747b82df485a6fa1e15c8fbaad"
  license "MIT"

  def install
    bin.install "intqual"
  end

  test do
    system "#{bin}/intqual", "--version"
  end
end
